#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Loading aesdchar module"
        aesdchar_load
	;;
  stop)
        echo -n "Unoading aesdchar module"
        aesdchar_unload
	;;

  *)
	echo "Usage: "$1" {start|stop}"
	exit 1
esac

exit 0